name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and test
      run: |
        npm ci
        npm run build
        npm test
    - name: Publish
      run: |
        echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
        npm publish || true
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
