name: Test

on: [push]

jobs:
  lint:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - run: npm ci --prefer-offline --no-audit
      - run: npm run lint:ci
     
  test:
    name: test

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci --prefer-offline --no-audit
    - run: npm run build --if-present
    - run: npm test
